version: '3.8'

services:
  mongodb:
    env_file: .env
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - esp_mongo:/var/lib/mysql
  service:
    env_file: .env
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  esp_mongo: